# Site settings
title: Deniz Çakar
title_description: Portfolio / Kişisel Site
email: denizcakar.90@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Uzunca bir açıklama
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://denizcakar.com" # the base hostname & protocol for your site
facebook_username: dnzcakar
twitter_username: dnzcakar
linkedin_username:  denizcakar

# Build settings
markdown: kramdown
